name: Main Workflow

on:
  push:
    branches:
      - branch
      - '**/*'  # To trigger on any branch, but the condition will restrict execution

jobs:
  call-reusable-workflow:
    uses: Krishnateja25/repo-workflows/.github/workflows/reusable-workflow.yml@main
    with:
      branch: ${{ github.ref }}
