# .github/workflows/main.yml
name: Main Repository Workflow

on:
  push:
    branches:
      - '**'  # Trigger on any branch push (or specify `main` if only on `main`)

jobs:
  call-reusable-workflow:
    uses:  Krishnateja25/repo-workflows/.github/workflows/reusable-workflow.yml@main  # Replace with the actual reusable workflow repo URL
    with:
      branch: ${{ github.ref_name }}  # Pass the current branch name





     